# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'mfp-dev-resource-manager-connection'
    azureContainerRegistry: '{"loginServer":"mfpdev.azurecr.io", "id" : "/subscriptions/b53c773b-b409-43bd-b2ea-95fe8fd9b5c2/resourceGroups/mfp-dev/providers/Microsoft.ContainerRegistry/registries/mfpdev"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifactType: 'pipeline'
    artifactName: 'mfp'
